name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g sass

      - name: Create dist directory structure
        run: |
          mkdir -p dist/src/styles
          mkdir -p dist/src/scripts
          mkdir -p dist/src/assets
          mkdir -p dist/src/locales

      - name: Build SCSS
        run: |
          sass src/styles/main.scss:dist/src/styles/main.css --style compressed
          cp src/styles/main.css dist/src/styles/

      - name: Copy and process files
        run: |
          cp -r src/scripts dist/src/
          cp -r src/assets dist/src/
          cp -r src/locales dist/src/
          cp index.html dist/

      - name: Update HTML file paths
        run: |
          sed -i 's|src/styles/main.scss|src/styles/main.css|g' dist/index.html
          sed -i 's|src/scripts|src/scripts|g' dist/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
